**Hamoye Stage B Quiz**

In [1]:
#Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('Skewness of Fuel Quantity Burned: {}\nKurtosis of Fuel Quantity Burned: {}'.format(np.round(skew,2),np.round(kurt,2)))

**Question 1**

**Question 2**

**Question 3**

**Question 4**

**Question 5**

**Question 6**

**Question 7**

**Question 8**

**Question 9**

**Question 10**

**Question 11**

**Question 12**

In [18]:
df = pd.read_csv(r'https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv')

In [19]:
df.describe(include = 'all')

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
unique,19735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-01-20 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,NaN,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,NaN,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,NaN,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,NaN,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,NaN,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,NaN,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

**Question 13**

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
date           19735 non-null object
Appliances     19735 non-null int64
lights         19735 non-null int64
T1             19735 non-null float64
RH_1           19735 non-null float64
T2             19735 non-null float64
RH_2           19735 non-null float64
T3             19735 non-null float64
RH_3           19735 non-null float64
T4             19735 non-null float64
RH_4           19735 non-null float64
T5             19735 non-null float64
RH_5           19735 non-null float64
T6             19735 non-null float64
RH_6           19735 non-null float64
T7             19735 non-null float64
RH_7           19735 non-null float64
T8             19735 non-null float64
RH_8           19735 non-null float64
T9             19735 non-null float64
RH_9           19735 non-null float64
T_out          19735 non-null float64
Press_mm_hg    19735 non-null float64
RH_out         19735 non-null float64
Windspeed      19735 non-null float64
Visibility     19735 non-null float64
Tdewpoint      19735 non-null float64
rv1            19735 non-null float64
rv2            19735 non-null float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [36]:
df

,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.530000,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.560000,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.500000,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.400000,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.400000,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
5,40,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,17.133333,...,17.000000,45.290000,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
6,50,19.890000,45.766667,19.200000,44.500000,19.790000,44.900000,18.890000,45.790000,17.100000,...,17.000000,45.290000,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,47.233763,47.233763
7,50,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,45.863333,17.100000,...,17.000000,45.290000,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890
8,40,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,45.790000,17.166667,...,17.000000,45.290000,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702
9,40,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,46.096667,17.100000,...,17.000000,45.290000,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314
10,70,19.926667,45.863333,19.356667,44.400000,19.790000,44.900000,18.890000,46.430000,17.100000,...,17.000000,45.290000,5.966667,734.366667,91.333333,5.666667,40.000000,4.633333,10.298729,10.298729
11,60,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,17.100000,...,16.890000,45.290000,5.983333,734.433333,91.166667,5.833333,40.000000,4.616667,8.827838,8.827838
12,50,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,17.100000,...,16.963333,45.290000,6.000000,734.500000,91.000000,6.000000,40.000000,4.600000,34.351142,34.351142
13,40,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,47.223333,17.100000,...,16.890000,45.326667,6.000000,734.616667,90.500000,6.000000,40.000000,4.516667,19.205186,19.205186
14,10,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,48.696667,17.100000,...,16.890000,45.345000,6.000000,734.733333,90.000000,6.000000,40.000000,4.433333,38.492071,38.492071
15,10,20.566667,53.893333,20.033333,46.756667,20.100000,48.466667,19.000000,48.490000,17.150000,...,16.890000,45.326667,6.000000,734.850000,89.500000,6.000000,40.000000,4.350000,24.884962,24.884962
16,10,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,48.156667,17.166667,...,16.890000,45.290000,6.000000,734.966667,89.000000,6.000000,40.000000,4.266667,35.880925,35.880925
17,30,20.856667,53.660000,20.200000,47.056667,20.200000,48.447500,18.890000,47.963333,17.200000,...,16.890000,45.290000,6.000000,735.083333,88.500000,6.000000,40.000000,4.183333,49.595305,49.595305
18,30,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,48.630000,17.200000,...,16.890000,45.200000,6.000000,735.200000,88.000000,6.000000,40.000000,4.100000,19.001759,19.001759
19,40,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,49.500000,17.593333,...,16.890000,45.200000,6.000000,735.233333,87.833333,6.000000,40.000000,4.066667,38.872261,38.872261
20,20,20.890000,48.433333,20.200000,45.722500,20.166667,47.300000,19.175000,49.947500,18.066667,...,16.890000,45.126667,6.000000,735.266667,87.666667,6.000000,40.000000,4.033333,46.735262,46.735262
21,40,20.963333,47.633333,20.260000,45.530000,20.200000,47.026667,19.260000,49.696667,17.666667,...,16.890000,45.126667,6.000000,735.300000,87.500000,6.000000,40.000000,4.000000,10.607126,10.607126
22,40,21.033333,47.063333,20.290000,45.223333,20.260000,46.826667,19.323333,49.166667,17.600000,...,16.890000,45.060000,6.000000,735.333333,87.333333,6.000000,40.000000,3.966667,32.583688,32.583688
23,40,21.100000,46.596667,20.356667,44.963333,20.290000,46.633333,19.390000,48.426667,17.566667,...,16.890000,45.000000,6.000000,735.366667,87.166667,6.000000,40.000000,3.933333,6.277755,6.277755
24,30,21.133333,46.060000,20.426667,44.760000,20.290000,46.433333,19.390000,48.193333,17.760000,...,16.890000,44.966667,6.000000,735.400000,87.000000,6.000000,40.000000,3.900000,13.361033,13.361033
25,20,21.200000,45.800000,20.500000,44.760000,20.390000,46.223333,19.390000,47.800000,18.356667,...,16.890000,44.900000,5.933333,735.466667,87.166667,6.000000,40.000000,3.866667,19.305705,19.305705
26,30,21.290000,45.900000,20.533333,45.090000,20.390000,46.090000,19.390000,47.560000,18.356667,...,16.890000,44.790000,5.866667,735.533333,87.333333,6.000000,40.000000,3.833333,0.669517,0.669517
27,20,21.356667,45.826667,20.666667,45.163333,20.390000,46.090000,19.390000,47.500000,18.600000,...,16.890000,44.790000,5.800000,735.600000,87.500000,6.000000,40.000000,3.800000,19.119398,19.119398
28,20,21.390000,45.690000,20.700000,45.060000,20.390000,46.090000,19.426667,47.993333,18.666667,...,16.890000,44.700000,5.733333,735.666667,87.666667,6.000000,40.000000,3.766667,43.484542,43.484542
29,20,21.500000,45.333333,20.700000,44.933333,20.390000,46.060000,19.566667,48.466667,18.823333,...,16.890000,44.700000,5.666667,735.733333,87.833333,6.000000,40.000000,3.733333,17.017450,17.017450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19705,0,25.033333,48.363333,26.528571,40.595714,28.496667,41.900000,24.500000,45.066667,22.760000,...,23.100000,46.500000,21.250000,756.050000,59.833333,1.166667,23.666667,13.100000,32.420348,32.420348
19706,0,25.166667,48.156667,26.600000,40.940000,28.290000,41.966667,24.500000,45.333333,22.790000,...,23.100000,46.500000,21.400000,756.000000,59.666667,1.333333,23.333333,13.200000,49.189027,49.189027
19707,0,25.323333,47.930000,26.600000,41.012857,28.200000,42.090000,24.533333,45.566667,22.790000,...,23.100000,46.522500,21.550000,755.950000,59.500000,1.500000,23.000000,13.300000,15.081162,15.081162
19708,0,25.390000,47.656667,26.600000,41.036000,28.200000,42.030000,24.600000,45.760000,22.790000,...,23.100000,46.530000,21.700000,755.900000,59.333333,1.666667,22.666667,13.400000,45.226866,45.226866
19709,0,25.500000,47.133333,26.600000,41.000000,28.200000,41.796667,24.600000,45.790000,22.856667,...,23.100000,46.530000,21.850000,755.850000,59.166667,1.833333,22.333333,13.500000,5.773431,5.773431
19710,10,25.500000,47.060000,26.540000,41.000000,28.200000,41.530000,24.600000,45.863333,22.890000,...,23.100000,46.530000,22.000000,755.800000,59.000000,2.000000,22.000000,13.600000,41.515044,41.515044
19711,0,25.600000,46.990000,26.512500,41.203750,28.200000,41.590000,24.633333,46.030000,22.890000,...,23.100000,46.530000,21.966667,755.800000,59.000000,2.000000,21.833333,13.550000,19.540642,19.540642
19712,0,25.600000,46.730000,26.437143,41.384286,28.426667,41.430000,24.700000,46.090000,22.890000,...,23.100000,46.590000,21.933333,755.800000,59.000000,2.000000,21.666667,13.500000,16.977597,16.977597
19713,0,25.566667,46.633333,26.370000,41.378000,28.566667,41.156667,24.700000,45.966667,22.890000,...,23.100000,46.626667,21.900000,755.800000,59.000000,2.000000,21.500000,13.450000,8.991420,8.991420
19714,0,25.500000,46.360000,26.318571,41.264286,28.566667,40.663333,24.700000,45.826667,22.890000,...,23.100000,46.700000,21.866667,755.800000,59.000000,2.000000,21.333333,13.400000,40.409885,40.409885
19715,0,25.500000,46.060000,26.350000,41.000000,28.426667,40.590000,24.666667,45.526667,22.890000,...,23.100000,46.590000,21.833333,755.800000,59.000000,2.000000,21.166667,13.350000,37.889086,37.889086
19716,0,25.500000,45.933333,26.277143,41.000000,28.356667,40.560000,24.666667,45.400000,22.945000,...,23.100000,46.590000,21.800000,755.800000,59.000000,2.000000,21.000000,13.300000,17.123315,17.123315
19717,0,25.500000,45.760000,26.200000,41.000000,28.290000,40.433333,24.700000,45.363333,23.000000,...,23.133333,46.590000,21.966667,755.750000,58.333333,2.000000,21.333333,13.283333,24.058432,24.058432
19718,0,25.500000,45.626667,26.171429,41.000000,28.260000,40.260000,24.700000,45.230000,23.000000,...,23.133333,46.590000,22.133333,755.700000,57.666667,2.000000,21.666667,13.266667,9.538671,9.538671
19719,0,25.500000,45.590000,26.100000,41.000000,28.200000,40.126667,24.700000,45.163333,23.033333,...,23.166667,46.590000,22.300000,755.650000,57.000000,2.000000,22.000000,13.250000,30.020685,30.020685
19720,0,25.500000,45.522500,26.100000,41.051429,28.200000,40.200000,24.700000,45.163333,23.033333,...,23.100000,46.590000,22.466667,755.600000,56.333333,2.000000,22.333333,13.233333,23.851737,23.851737
19721,0,25.500000,45.633333,26.080000,41.196000,28.133333,40.260000,24.700000,45.300000,23.033333,...,23.200000,46.590000,22.633333,755.550000,55.666667,2.000000,22.666667,13.216667,47.981309,47.981309
19722,0,25.500000,45.730000,26.000000,41.428571,28.100000,40.433333,24.700000,45.433333,23.100000,...,23.200000,46.590000,22.800000,755.500000,55.000000,2.000000,23.000000,13.200000,18.215602,18.215602
19723,0,25.500000,45.790000,26.000000,41.590000,28.100000,40.560000,24.700000,45.500000,23.100000,...,23.160000,46.590000,22.833333,755.450000,55.000000,2.166667,22.833333,13.233333,38.751594,38.751594
19724,0,25.500000,45.933333,26.000000,41.652857,28.000000,40.700000,24.700000,45.466667,23.100000,...,23.200000,46.621429,22.866667,755.400000,55.000000,2.333333,22.666667,13.266667,32.306224,32.306224
19725,0,25.426667,46.060000,26.000000,41.700000,28.000000,40.760000,24.700000,45.400000,23.200000,...,23.200000,46.700000,22.900000,755.350000,55.000000,2.500000,22.500000,13.300000,23.009520,23.009520
19726,0,25.500000,46.530000,26.000000,41.725714,27.856667,40.500000,24.700000,45.500000,23.200000,...,23.200000,46.652857,22.933333,755.300000,55.000000,2.666667,22.333333,13.333333,25.296732,25.296732
19727,0,25.500000,47.456667,26.000000,42.320000,27.663333,40.693333,24.700000,45.560000,23.200000,...,23.200000,46.718000,22.966667,755.250000,55.000000,2.833333,22.166667,13.366667,1.796395,1.796395
19728,0,25.600000,47.193333,25.968571,42.528571,27.390000,41.030000,24.700000,45.626667,23.200000,...,23.200000,46.751429,23.000000,755.200000,55.000000,3.000000,22.000000,13.400000,18.248201,18.248201
19729,0,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,45.626667,23.200000,...,23.200000,46.745000,22.866667,755.200000,55.333333,3.166667,22.833333,13.366667,16.966162,16.966162
19730,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.790000,22.733333,755.200000,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.790000,22.600000,755.200000,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.790000,22.466667,755.200000,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.817500,22.333333,755.200000,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.845000,22.200000,755.200000,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [37]:
new_df = df

In [38]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
lights         19735 non-null int64
T1             19735 non-null float64
RH_1           19735 non-null float64
T2             19735 non-null float64
RH_2           19735 non-null float64
T3             19735 non-null float64
RH_3           19735 non-null float64
T4             19735 non-null float64
RH_4           19735 non-null float64
T5             19735 non-null float64
RH_5           19735 non-null float64
T6             19735 non-null float64
RH_6           19735 non-null float64
T7             19735 non-null float64
RH_7           19735 non-null float64
T8             19735 non-null float64
RH_8           19735 non-null float64
T9             19735 non-null float64
RH_9           19735 non-null float64
T_out          19735 non-null float64
Press_mm_hg    19735 non-null float64
RH_out         19735 non-null float64
Windspeed      19735 non-null float64
Visibility     19735 non-null float64
Tdewpoint      19735 non-null float64
rv1            19735 non-null float64
rv2            19735 non-null float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [39]:
new_df.drop(['lights'], axis=1, inplace=True)

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

normalised_df = pd.DataFrame(scaler.fit_transform(df), columns=new_df.columns)

target_v = normalised_df['T6']

In [66]:
features =normalised_df[['T2']]

In [67]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target_v, test_size = 0.3, random_state = 42)

In [68]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()

#fit the model to the training dataset

linear_model.fit(X_train, y_train)

#obtain predictions

predicted_values = linear_model.predict(X_test)

In [71]:
from sklearn.metrics import r2_score

r2_score = r2_score(y_test, predicted_values)

round(r2_score, 2)

0.64

In [69]:
#MAE

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, predicted_values)

round(mae, 2)

0.08

In [70]:

rss = np.sum(np.square(y_test - predicted_values))

round(rss, 2)

66.12

In [73]:
from sklearn.metrics import  mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, predicted_values))

round(rmse, 3)

0.106

In [74]:
from sklearn.linear_model import Ridge, Lasso